"""Shared rendering helpers for views."""

from __future__ import annotations

WARNING = (
    "_Generated from the master artifact. **Do not edit this file** — edits are lost "
    "on the next regeneration. Spotted an error? Report it, and the fix reaches "
    "everyone's copy._"
)


def header(artifact: dict, view_label: str) -> list[str]:
    session = artifact.get("session") or {}
    title = " — ".join(
        part for part in [session.get("course"), session.get("topic")] if part
    ) or "Class notes"

    meta = [
        session.get("date"),
        session.get("instructor"),
        f"{session.get('duration_seconds', 0) / 60:.0f} min" if session.get("duration_seconds") else None,
        view_label,
    ]
    lines = [f"# {title}", "", " · ".join(m for m in meta if m), ""]

    headline = (artifact.get("summary") or {}).get("headline")
    if headline:
        lines += [f"> {headline}", ""]
    return lines


def diagram_block(artifact: dict, heading: str = "## The shape of it") -> list[str]:
    mermaid = (artifact.get("diagram") or {}).get("mermaid", "").strip()
    if not mermaid:
        return []
    return [heading, "", "```mermaid", mermaid, "```", ""]


def slide_ref(section: dict) -> str:
    refs = section.get("slide_refs") or []
    if not refs:
        return ""
    if len(refs) == 1:
        return f"slide {refs[0]}"
    return f"slides {min(refs)}–{max(refs)}"


def section_meta(section: dict) -> str:
    parts = [slide_ref(section), section.get("time_range")]
    joined = " · ".join(p for p in parts if p)
    return f" _({joined})_" if joined else ""


def video_block(artifact: dict, heading: str) -> list[str]:
    videos = artifact.get("videos") or []
    if not videos:
        return []
    lines = [heading, ""]
    for entry in videos:
        lines.append(f"**{entry['concept']}** — {entry.get('why', '')}")
        for link in entry.get("links") or []:
            lines.append(f"- [{link['title']}]({link['url']}) — {link['channel']}")
        if not entry.get("links"):
            lines.append(f"- [Search YouTube for this]({entry['search_url']})")
        lines.append("")
    return lines


def footer(artifact: dict) -> list[str]:
    by = artifact.get("generated_by") or {}
    stamp = f"v{artifact.get('version', '?')} · {artifact.get('generated_at', '')}"
    model = f"{by.get('provider', '?')}/{by.get('model', '?')}"
    lines = ["---", "", WARNING, ""]
    if by.get("provider") == "fake":
        lines = [
            "---",
            "",
            "> **⚠ Placeholder output.** This ran with the `fake` provider — the structure "
            "is real, the content is not. Do not send this to a class.",
            "",
        ] + lines[2:]
    lines.append(f"_{stamp} · {model}_")
    return lines
